version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: learnai_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: learnai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Change to 5433:5432

  backend:
    build: ./backend
    environment:
      - OPENAI_API_KEY=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
      - JWT_SECRET=your_jwt_secret
      - DATABASE_URL=postgres://learnai_user:password@postgres:5432/learnai
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"

volumes:
  postgres_data:
