version: '3'

services:
  backend:
    # build: ./backend
    image: ghcr.io/utsc-cscc09-programming-on-the-web/project-connect-backend:latest
    container_name: project-connect-backend
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MONGODB_URI: ${MONGODB_URI}
      VIRTUAL_HOST: server.utsc-learnai.tech
      LETSENCRYPT_HOST: server.utsc-learnai.tech
      NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"

  frontend:
    # build: ./frontend
    image: ghcr.io/utsc-cscc09-programming-on-the-web/project-connect-frontend:latest
    container_name: project-connect-frontend
    expose:
      - "80"
    restart: always
    depends_on:
      - backend
    environment:
      - VIRTUAL_HOST=utsc-learnai.tech
      - LETSENCRYPT_HOST=utsc-learnai.tech

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
        - NGINX_PROXY_CONTAINER=nginx-proxy
        - DEFAULT_EMAIL=vedat.goktepe@mail.utoronto.ca
